version: '3.8'

services:
  publisher:
    restart: unless-stopped
    depends_on:
      - gateway
    image: andriiuni/events:latest
    environment:
      EVENT_ENDPOINT: http://gateway:3000/events
    networks:
      - app-network

  gateway:
    restart: unless-stopped
    depends_on:
      - nats
      - prisma-migrate
      - postgres
    build:
      context: gateway
    environment:
      NODE_ENV: production
      NATS_URL: nats:4222
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/liveness']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway-processor:
    restart: unless-stopped
    depends_on:
      - nats
      - prisma-migrate
      - postgres
    build:
      context: gateway-processor
    environment:
      NODE_ENV: production
      NATS_URL: nats:4222
      DATABASE_URL: postgres://admin:123456@postgres/main
      OUTBOX_POLL_INTERVAL_MS: 500
      OUTBOX_BATCH_SIZE: 500
      OUTBOX_MAX_RETRIES: 2
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/liveness']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  nats:
    restart: unless-stopped
    image: nats:latest
    command: ['--jetstream', '--store_dir', '/data/jetstream', '-m', '8222']
    volumes:
      - nats-data:/data/jetstream
    networks:
      - app-network

  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: main
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  fb-collector:
    restart: unless-stopped
    depends_on:
      - prisma-migrate
      - nats
      - postgres
    build:
      context: fb-collector
    environment:
      NODE_ENV: production
      NATS_URL: nats:4222
      NATS_STREAM: FACEBOOK
      NATS_CONSUMER: fb-collector
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/liveness']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  ttk-collector:
    restart: unless-stopped
    depends_on:
      - prisma-migrate
      - nats
      - postgres
    build:
      context: ttk-collector
    environment:
      NODE_ENV: production
      NATS_URL: nats:4222
      NATS_STREAM: TIKTOK
      NATS_CONSUMER: ttk-collector
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/liveness']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  reporter:
    restart: unless-stopped
    depends_on:
      - prisma-migrate
      - postgres
    build:
      context: reporter
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health/liveness']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-network

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      - app-network

  prisma-migrate:
    build: migration-runner
    environment:
      DATABASE_URL: postgres://admin:123456@postgres/main
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  nats-data:
  postgres-data:
  grafana-data:

networks:
  app-network:
