version: "3.8"

services:
  publisher:
    depends_on:
      - gateway
      - fb-collector
      - ttk-collector
    image: andriiuni/events
    environment:
      EVENT_ENDPOINT: http://gateway:3000/events
    networks:
      - app-network
  gateway:
    depends_on:
      - nats
      - postgres
    build:
      context: gateway
#    command: npm run start:dev
#    volumes:
#      - ./gateway:/app
    environment:
      NODE_ENV: development
      NATS_URL: nats:4222
    ports:
      - "3000:3000"
    networks:
      - app-network
  nats:
    image: nats:latest
    command: [
      "--jetstream",
      "--store_dir", "/data/jetstream"
    ]
    volumes:
      - nats-data:/data/jetstream
    networks:
      - app-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: main
    ports:
      - "5050:5432"
    networks:
      app-network:
    volumes:
      - postgres-data:/var/lib/postgresql/data
  fb-collector:
    depends_on:
      - postgres
      - nats
    build:
      context: fb-collector
#    command: npm run start:dev
#    volumes:
#      - ./fb-collector:/app
#      - ./fb-collector/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      NATS_URL: nats:4222
      NATS_STREAM: FACEBOOK
      NATS_CONSUMER: fb-collector
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network
  ttk-collector:
    depends_on:
      - postgres
      - nats
    build:
      context: ttk-collector
    environment:
      NODE_ENV: development
      NATS_URL: nats:4222
      NATS_STREAM: TIKTOK
      NATS_CONSUMER: ttk-collector
      DATABASE_URL: postgres://admin:123456@postgres/main
    networks:
      - app-network

networks:
  app-network:
volumes:
  nats-data:
  postgres-data: