version: "3.8"

services:
  publisher:
    image: andriiuni/events
    environment:
      EVENT_ENDPOINT: http://gateway:3000/events
    networks:
      - app-network
  gateway:
    depends_on:
      - publisher
    build:
      context: gateway
    command: npm run start:dev
    volumes:
      - ./gateway:/app
    environment:
      NODE_ENV: development
      NATS_URL: nats:4222
    ports:
      - "3000:3000"
    networks:
      - app-network
  nats:
    image: nats:latest
    command: [
      "--jetstream",
      "--store_dir", "/data/jetstream"
    ]
    volumes:
      - nats-data:/data/jetstream
    networks:
      - app-network

networks:
  app-network:
volumes:
  nats-data: