global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
#  - job_name: 'fb_collector'
#    static_configs:
#      - targets: ['fb-collector:3000']
#
#  - job_name: 'ttk_collector'
#    static_configs:
#      - targets: ['ttk-collector:3000']
#
#  - job_name: 'reporter'
#    static_configs:
#      - targets: ['reporter:3000']