{
 "title": "Collectors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Accepted Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(fb_collector_events_accepted_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ttk_collector_events_accepted_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(fb_collector_events_failed_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ttk_collector_events_failed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fb-collector Processed Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(fb_collector_events_processed_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ttk_collector_events_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}