{
 "title": "Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(gateway_events_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(gateway_events_failed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(gateway_events_accepted_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbox Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "rate(gateway_outbox_events_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}