{
 "title": "Reports Latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Events Report Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(reporter_report_latency_seconds_sum{report_type=\"events\"}[1m])) \r\n/ \r\nsum(rate(reporter_report_latency_seconds_count{report_type=\"events\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue Report Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(reporter_report_latency_seconds_sum{report_type=\"revenue\"}[1m])) \r\n/ \r\nsum(rate(reporter_report_latency_seconds_count{report_type=\"revenue\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Demographic Report Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(reporter_report_latency_seconds_sum{report_type=\"demographic\"}[1m])) \r\n/ \r\nsum(rate(reporter_report_latency_seconds_count{report_type=\"demographic\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}